# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Rider' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'
  
  # React Native third party dependencies podspecs
  # pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  # pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'


  # pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|

#     # The following is needed to ensure the "archive" step works in XCode.
#     # It removes React & Yoga from the Pods project, as it is already included in the main project.
#     # Without this, you'd see errors when you archive like:
#     # "Multiple commands produce ... libReact.a"
#     # "Multiple commands produce ... libyoga.a"

#     targets_to_ignore = %w(React yoga)
    
#     if targets_to_ignore.include? target.name
#       target.remove_from_project
#     end

#   end
# end